install.packages("magrittr")
install.packages("dplyr")
install.packages("sqldf")
install.packages("janitor")
install.packages("dplyr")
install.packages("reshape2")
install.packages("ggplot2")
library(dplyr)
library(stringr)
library(magrittr)
library(dplyr)
library(janitor)
library(ggplot2)
require(sqldf)
require(reshape2)
Email<-read.csv("/Users/rishabhjamar/Downloads/join_data.csv",header=T,stringsAsFactors = F)
View(Email)
df<-as.data.frame(Email)
View(df)
df1<- sqldf("select \"Element.Id\" as Element_id, Action, count(Action) as 'Number_of_Emails_Delivered', \"Email.Date\" as Email_date from df where Action='emailDelivered' group by \"Email.Date\", \"Element.Id\", Action")
View(df1)
df2<- sqldf("select \"Element.Id\" as Element_id, Action, count(Action) as 'Number_of_Emails_Opened', \"Email.Date\" as Email_date from df where Action='emailOpened' group by \"Email.Date\", \"Element.Id\", Action")
View(df2)
df3<- sqldf("select df1.Element_id,df1.Number_of_Emails_Delivered,df2.Number_of_Emails_Opened from df1,df2 where df1.Element_id=df2.Element_id and df1.Email_date=df2.Email_date")
View(df3)
ggplot(data =df3, aes(x=Element_id, y=Number_of_Emails_Delivered)) + geom_point()
sqldf("select Avg(Number_of_Emails_Delivered) from df3")

